baseURL = 'https://bernardmcweeney.com/'
languageCode = 'en-us'
title = 'Bernard McWeeney'
theme = 'TwentyTwentyFive'

  
[params]
  description = "Welcome to my personal blog where I share my thoughts on technology, farming, and Irish culture."
  about = "Hello! I'm Bernard McWeeney, a passionate individual with interests spanning technology, farming, music, and Irish history. Through this blog, I share my journey and insights across these diverse fields."
  logo = "/images/logo.jpg"  # Optional

  [[params.social]]
    platform = "GitHub"
    URL = "https://github.com/BernardMcWeeney"
    icon = "fab fa-github"
  
  [[params.social]]
    platform = "Twitter / X"
    URL = "https://x.com/BMcWeeneyIE"
    icon = "fab fa-x-twitter"

  [[params.social]]
    platform = "Bluesky"
    URL = "https://bsky.app/profile/bernardmcweeney.bsky.social"
    icon = "fab fa-bluesky"
  
  [[params.social]]
    platform = "Mastodon"
    URL = "https://mastodon.social/@bernardmcweeney"
    icon = "fab fa-mastodon"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 30
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 40
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 60
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 70

[params.dailyTracks]
monday = "6eUWC6rP8Rcd9TfpjCbEJG"
tuesday = "5EabbLQZbdhCqG6aK9PFLU"
wednesday = "4mPx3lVrvLPMFK1NvLezB2"
thursday = "08Hncs1L3PYHpfsb8sYdmQ"
friday = "0MXmiqd7zoXxv6Gqn9ahhQ"
saturday = "6jaAQqNv2iWQbx5SmYtHx4"
sunday = "0gHvrWN5ZQPDqn3QnpI5DD"