name = 'TwentyTwentyFive'
license = 'MIT'
licenselink = 'https://github.com/BernardMcWeeney/TwentyTwentyFive/LICENSE'
description = 'A modern, responsive Hugo theme focused on personal blogging with support for multiple content types and dynamic widgets'

homepage = 'https://github.com/BernardMcWeeney/TwentyTwentyFive'
demosite = 'https://bernardmcweeney.com'

tags = ['blog', 'personal', 'responsive', 'modern', 'tailwind']
features = [
    'mobile-first',
    'responsive',
    'tailwind css',
    'dark mode',
    'widgets',
    'multiple content types',
    'social media integration'
]

[author]
    name = 'Bernard McWeeney'
    homepage = 'https://bernardmcweeney.com'